In [1]:
a = 3
b = 5 
a + b

8

In [2]:
import pandas as pd

  regionid   qty
0      A01   100

In [ ]:
# exception 로직추가

try:
    inDf = pd.read_csv("./dataset/sample.txt")
    inDf
except Exception as e:
    print(e)

In [5]:
inDf = pd.read_csv("./dataset/sample.txt")
inDf

  regionid   qty
0      A01   100